Basic Legion Implementation: Hekzder Fuming edition
Mojave-Sun/mojave-sun pull request #160
Opened 2020-11-02 05:47 UTC by ProfessorPopoff

![image](https://user-images.githubusercontent.com/51188571/97834052-d7764a00-1ca4-11eb-89fb-9c6e05fb18bc.png)

This PR adds the following clothing as well as the basic job implementation for the Legion. Balancing is not Hekz-Certified, but he'll do it himself, as Mars intended.

2020-11-02 06:52 UTC, uomo91 requested changes

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Praetorian"
```suggestion
/obj/effect/landmark/start/f13/legion_praetorian
	name = "Legion Praetorian"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Centurion"
```suggestion
/obj/effect/landmark/start/f13/legion_centurion
	name = "Legion Centurion"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Veteran Decanus"
```suggestion
/obj/effect/landmark/start/f13/legion_veteran_decanus
	name = "Legion Veteran Decanus"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Prime Decanus"
```suggestion
/obj/effect/landmark/start/f13/legion_prime_decanus
	name = "Legion Prime Decanus"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Recruit Decanus"
```suggestion
/obj/effect/landmark/start/f13/legion_recruit_decanus
	name = "Legion Recruit Decanus"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Veteran Legionary"
```suggestion
/obj/effect/landmark/start/f13/legion_veteran_legionary
	name = "Legion Veteran Legionary"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Speculatore"
```suggestion
/obj/effect/landmark/start/f13/legion_speculatore
	name = "Legion Speculatore"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Explorer"
```suggestion
/obj/effect/landmark/start/f13/legion_explorer
	name = "Legion Explorer"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/effects/landmarks.dm
> +	name = "Scout"
```suggestion
/obj/effect/landmark/start/f13/legion_scout
	name = "Legion Scout"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/feet/fallout_shoes.dm
> +	desc = "Generic boots worn by legionaires."
```suggestion
	name = "generic Legion boots"
	desc = "Generic boots worn by Legionaries."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/feet/fallout_shoes.dm
> +	desc = "A pair of cleats, often sported by mobility focused legionaries."
```suggestion
	desc = "A pair of cleats, often sported by mobility focused Legionaries."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/gloves/gloves.dm
> +    desc = "Generic gloves worn by legionaires."
```suggestion
    desc = "Generic gloves worn by Legionaries."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	desc = "A helmet used by Prime legionaries. It's pretty dense."
```suggestion
	desc = "A helmet used by Prime Legionaries. It's pretty dense."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "legion veteran helmet"
```suggestion
	name = "\improper Legion veteran helmet"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	desc = "A helmet used by Veteran legionaries. It's got a face guard to keep you from bumping into things!"
```suggestion
	desc = "A helmet used by Veteran Legionaries. It's got a face guard to keep you from bumping into things!"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	desc = "A helmet used by recruit decanii of the Legion. It sports some brown feathers to signify lesser leadership"
```suggestion
	desc = "A helmet used by recruit decanii of the Legion. It sports some brown feathers to signify lesser leadership."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	desc = "A helmet used by prime decanii of the Legion. It's got black feathers to signify a moderate rank"
```suggestion
	desc = "A helmet used by prime decanii of the Legion. It's got black feathers to signify a moderate rank."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	desc = "A donned by only the most esteemed Centurions in the Legion. Impressive!"
```suggestion
	desc = "A helmet donned by only the most esteemed Centurions in the Legion. Impressive!"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "praetorian helmet"
```suggestion
	name = "\improper Legion praetorian helmet"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "legion scout helmet"
```suggestion
	name = "\improper Legion scout helmet"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "legion explorer cap"
```suggestion
	name = "\improper Legion explorer cap"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "manny mammoth head"
```suggestion
	name = "\improper Manny Mammoth head"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/masks/masks.dm
> +	desc = "A simple cloth mask often used by legionares for an assortment of reasons."
```suggestion
	desc = "A simple cloth mask often used by Legionaries for an assortment of reasons."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/masks/masks.dm
> +	name = "legion speculatore mask"
```suggestion
	name = "\improper Legion speculatore mask"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/masks/masks.dm
> +	desc = "A mask only worn by the near unheard of Speculatores of the Legion. Whatever metal it's made of is good for deflecting bullets received to the face- If you can hit them."
```suggestion
	desc = "A mask only worn by the near unheard of Speculatores of the Legion. Whatever metal it's made of is good for deflecting bullets received to the face - if you can hit them."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/neck/neck.dm
> +	desc = "This shouldn't really exist"
```suggestion
```

These are redundant definitions.

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/neck/neck.dm
> +	desc = "A white half cloak used by legionaries. Good for snowy environments."
```suggestion
	desc = "A white half cloak used by Legionaries. Good for snowy environments."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/neck/neck.dm
> +	desc = "A red half cloak worn by certain legionaires. It's got the symbol of the bull on its back."
```suggestion
	desc = "A red half cloak worn by certain Legionaries. It's got the symbol of the bull on its back."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/neck/neck.dm
> +	desc = "A brown half cloak worn by certain legionaires. It's got the symbol of the bull on its back."
```suggestion
	desc = "A brown half cloak worn by certain Legionaries. It's got the symbol of the bull on its back."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/neck/neck.dm
> +	desc = "a hooded cloak worn by the elusive Speculatores of Caesar's Legion. It's good at blocking the sun's rays."
```suggestion
	desc = "A hooded cloak worn by the elusive Speculatores of Caesar's Legion. It's good at blocking the sun's rays."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
>  	name = "legion recruit armor"
```suggestion
	name = "\improper Legion recruit armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
>  	name = "legion prime armor"
```suggestion
	name = "\improper Legion prime armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
>  	name = "legion veteran armor"
```suggestion
	name = "\improper Legion veteran armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
>  	name = "legion scout armor"
```suggestion
	name = "\improper Legion scout armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
>  	name = "legion explorer armor"
```suggestion
	name = "\improper Legion explorer armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
> +	name = "legion explorer armor"
```suggestion
	name = "\improper Legion explorer armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
>  	name = "legion vexillarius armor"
```suggestion
	name = "\improper Legion vexillarius armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
> +	name = "legion praetorian armor"
```suggestion
	name = "\improper Legion praetorian armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
>  	name = "legion centurion armor"
```suggestion
	name = "\improper Legion centurion armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "red legion fatigues"
```suggestion
	name = "red Legion fatigues"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "stealthy red legion fatigues"
```suggestion
	name = "stealthy red Legion fatigues"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "padded red legion fatigues"
```suggestion
	name = "padded red Legion fatigues"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "brown legion fatigues"
```suggestion
	name = "brown Legion fatigues"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "padded brown legion fatigues"
```suggestion
	name = "padded brown Legion fatigues"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "white legion fatigues"
```suggestion
	name = "white Legion fatigues"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "stealthy white legion fatigues"
```suggestion
	name = "stealthy white Legion fatigues"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "padded white legion fatigues"
```suggestion
	name = "padded white Legion fatigues"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	name = "slave Rags"
```suggestion
	name = "slave rags"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
> +	desc = "Rags indicating you've been given the highest honor the Legion can bestow upon you- Servitude. Ave Caesar!"
```suggestion
	desc = "Rags indicating you've been given the highest honor the Legion can bestow upon you - servitude. Ave Caesar!"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/jobs/job_types/legion/_legion.dm
> +	forbid = "Caesar's Legion forbids: Chem usage, Over-reliance on technology of all forms."
```suggestion
	forbid = "Caesar's Legion forbids: chem usage, over-reliance on technology of all forms."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/jobs/job_types/legion/recruitlegionary.dm
> +	description = "Assist the higher ranks in handling your soldiers, keep them in line and focused on the goals at hand."
```suggestion
	description = "Fight in the name of Caesar, and claim the lands for the Bull! Listen to your superiors, they will guide you to victory."
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/jobs/job_types/legion/recruitlegionary.dm
> +	name = "_Legion Recruit Legionary"
```suggestion
	name = "_Legion Recruit"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/gloves/gloves.dm
> +    name = "generic legion gloves"
```suggestion
    name = "generic Legion gloves"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "legion prime helmet"
```suggestion
	name = "\improper Legion prime helmet"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "recruit decanus helmet"
```suggestion
	name = "\improper Legion recruit decanus helmet"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "prime decanus helmet"
```suggestion
	name = "\improper Legion prime decanus helmet"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "veteran decanus helmet"
```suggestion
	name = "\improper Legion veteran decanus helmet"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/head/helmet.dm
> +	name = "centurion helmet"
```suggestion
	name = "\improper Legion centurion helmet"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
> +	name = "standard legion armor"
```suggestion
	name = "standard Legion armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/suits/armor.dm
>  	name = "legion veteran armor"
```suggestion
	name = "\improper Legion veteran armor"
```

2020-11-02 06:52 UTC, uomo91 commented on fallout/items/clothing/under/legion/under.dm
>  	name = "legion fatigues"
```suggestion
	name = "\improper Legion fatigues"
```

2020-11-02 07:56 UTC, merged

2020-11-06 08:25 UTC, Mannybrado commented
*fart sound
*poop sound
*vomit sound