Fixes NCR not showing up in latejoin menu.
Mojave-Sun/mojave-sun pull request #188
Opened 2020-11-25 01:57 UTC by uomo91

## About The Pull Request

Somebody (I think myself) added "NCR" to the beginning of their job titles, this was causing them to be left out of the latejoin proc.

## Why It's Good For The Game

Bugs bad.

2020-11-25 16:52 UTC, Hekzder commented
I'd prefer the prefix be left, I'm not sure exactly what the issue is but if we can solve it and keep the prefix that would be ideal.

2020-11-25 23:06 UTC, uomo91 commented
> I'd prefer the prefix be left, I'm not sure exactly what the issue is but if we can solve it and keep the prefix that would be ideal.

The only place this is visible is on the job preferences menu.
And if we do this for the NCR, we should do it for all the jobs.

2020-12-03 06:15 UTC, uomo91 commented
Oops.

2020-12-03 18:05 UTC, Hekzder requested changes
Prefixes are good, the base Legionary jobs don't really need the prefix, since they have Legion/Legionary in the name by default. 

Recruit Legionary, Prime Legionary, etc. sounds much better than "Prime Legion", while still making it pretty obvious that you're playing as the Legion.

2020-12-03 18:05 UTC, Hekzder commented on mojave/jobs/job_types/legion/primelegionary.dm
> +	title = "Legion Prime"
```suggestion
	title = "Prime Legionary"
```

2020-12-03 18:05 UTC, Hekzder commented on mojave/jobs/job_types/legion/recruitlegionary.dm
> +	title = "Legion Recruit"
```suggestion
	title = "Recruit Legionary"
```

2020-12-03 18:05 UTC, Hekzder commented on mojave/jobs/job_types/legion/veteranlegionary.dm
> +	title = "Legion Veteran"
```suggestion
	title = "Veteran Legionary"
```

2020-12-03 21:29 UTC, Hekzder approved these changes
This should be fine to merge now, once we get the CI stuff sorted.

2020-12-03 21:57 UTC, merged