MS Tall Wall Update #002
Mojave-Sun/mojave-sun pull request #192
Opened 2020-11-26 12:34 UTC by scarwolff

## About The Pull Request

Adds tall walls for mappers (not functional yet, we gotta wait on TG), also fixes the stupid smoothing system and adds a single tall door.

## Why It's Good For The Game

2020-11-27 03:55 UTC, uomo91 commented
Will try to playtest this soon, until then needs approval from Infra.

2020-11-29 03:54 UTC, uomo91 requested changes
Low walls are not getting proper `icon_state`'s.

2020-11-29 08:40 UTC, infraredbaron commented
Brick wall and low brick wall doesn't match. Use proper walls, instead of crayon colored sandstone walls

2020-12-02 08:18 UTC, infraredbaron approved these changes
Sprites are good enough to serve their purpose - allow mappers to actually work with something.

2020-12-03 05:26 UTC, uomo91 requested changes

2020-12-03 05:26 UTC, uomo91 commented on mojave/structures/doors.dm
> +		pixel_x = 6
Make this a switch, and also I think this should be getting done in initialize(), I don't think the code needs to be rerun every single time the door is opened or closed, just when the door is initialized.

2020-12-03 05:44 UTC, uomo91 requested changes
The doors are not animating properly.

Also these are missing sprites:
/turf/closed/wall/ms13/adobe
/obj/structure/table/low_wall/reinforced/bunker
Unclear to me if they're placeholders that don't have sprites yet or what.

2020-12-03 05:46 UTC, uomo91 requested changes
Doors are layering very oddly.

2020-12-07 01:40 UTC, uomo91 requested changes
The doors still just don't function, and it seems Infra has to make a small tweak to the low wall templates.

2020-12-22 17:00 UTC, Koshenko commented
Door related code has been commented out until more work is done upstream on tall walls.  Leaving the door assets is fine for now.  Low walls reconfigured to properly smooth at 32x32.  Since this is mostly for the benefit of the mappers as a source of placeholders, I'm going to go ahead and merge this.

2020-12-22 17:00 UTC, merged