Adds in the Melee weapons
Mojave-Sun/mojave-sun pull request #294
Opened 2021-04-04 01:49 UTC by ProfessorPopoff

Uhhh. **Yo.**

Submitting this as a draft for now. I've got it along decently, I'm mainly trying to iron out exactly how I can get all the wielded weapons to function, as well as some of the special weapons. Roughly half done, will update this as I go along. For now, witness peak badcode and the awesome sprites provided by Infra, along with a bit of sprinkled in certified codersprite to compensate for the lack of toggled variants. 
![image](https://user-images.githubusercontent.com/51188571/113496309-62fb3d80-94c6-11eb-9325-13943a292904.png)
![image](https://user-images.githubusercontent.com/51188571/113496310-64c50100-94c6-11eb-9402-f5b90a4b981c.png)

2021-04-04 02:56 UTC, Hekzder requested changes
Just some minor typo level stuff.

2021-04-04 02:56 UTC, Hekzder commented on mojave/items/melee/axe.dm
> +	name = "fire Axe"
```suggestion
	name = "fireaxe"
```

2021-04-04 02:56 UTC, Hekzder commented on mojave/items/melee/knife.dm
> +	desc = "A well made, serrated combat knife. Very effective at wounding. It's got a light frame, with a rifle lug to potentiall attach to a matching rifle."
```suggestion
	desc = "A well made, serrated combat knife. Very effective at wounding. It's got a light frame, with a rifle lug to potentially attach to a matching rifle."
```

2021-04-04 02:56 UTC, Hekzder commented on mojave/items/melee/knife.dm
> +	name = "hunting"
```suggestion
	name = "hunting knife"
```

2021-04-22 06:12 UTC, ProfessorPopoff commented
Well well well. The time approaches. I think I've just about got everything done here. I'm opening this for review, may god have mercy. I added everything to the best of my ability and also learned many things over the last half month. God be praised it's over, though. Overall, this has added a TON of melee weapons of varying types. Hekzder will probably want to comb over this one, as I have even less of an idea of what the values do than I do with the armours. 

![image](https://user-images.githubusercontent.com/51188571/115664692-2629a600-a310-11eb-8c7e-894b56d2db9a.png)
![image](https://user-images.githubusercontent.com/51188571/115664708-2de94a80-a310-11eb-81bc-597f2ac8b932.png)
![image](https://user-images.githubusercontent.com/51188571/115664722-32156800-a310-11eb-8ecc-48bd2adca190.png)

As you can see, the brick and the flare are T4. Direct further questions to Koshenko. Good day.

2021-04-22 19:33 UTC, Mannybrado commented
hm... but did you make a google spreadsheet calculating all of the damage, dps, attack delay, armor piercing, and wound damage all of them do to multiple types of armor of every tier?

2021-04-22 19:35 UTC, Mannybrado commented
> Well well well. The time approaches. I think I've just about got everything done here. I'm opening this for review, may god have mercy. I added everything to the best of my ability and also learned many things over the last half month. God be praised it's over, though. Overall, this has added a TON of melee weapons of varying types. Hekzder will probably want to comb over this one, as I have even less of an idea of what the values do than I do with the armours.
> 
> ![image](https://user-images.githubusercontent.com/51188571/115664692-2629a600-a310-11eb-8c7e-894b56d2db9a.png)
> ![image](https://user-images.githubusercontent.com/51188571/115664708-2de94a80-a310-11eb-81bc-597f2ac8b932.png)
> ![image](https://user-images.githubusercontent.com/51188571/115664722-32156800-a310-11eb-8ecc-48bd2adca190.png)
> 
> As you can see, the brick and the flare are T4. Direct further questions to Koshenko. Good day.

btw you included the normal hammer in the twohand category :\\\\\\\\\\\\\\\\\\\\\

2021-04-23 00:30 UTC, ProfessorPopoff commented
> btw you included the normal hammer in the twohand category :\\\\\\\\\\\

Meh. It happens.

2021-05-31 21:14 UTC, Hekzder approved these changes
Balance TBD but there isn't much of a reason not to merge this so everything is at least in the files and more organized.

2021-05-31 21:16 UTC, merged